version: 2.1
workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: circleci/node:14.13.0
    steps:
      - checkout
      - run: sudo apt update && sudo apt install rsync sshpass
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-cache
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          command: yarn download && GATSBY_CPU_COUNT=1 yarn build
          no_output_timeout: 20m
      - save_cache:
          key: v1-cache
          paths:
            - public/cache

#      - deploy:
#          name: 'Publish Website Could JP_1_HOST'
#          command:
#            ssh-keyscan "${HOST_JP_1_IP}" >> ~/.ssh/known_hosts 2>/dev/null;
#            sshpass -p ${HOST_JP_1_PASSWORD}  rsync -avz -e 'ssh -p 22' --delete --exclude css --exclude js --exclude images public/ "${HOST_JP_1_USER}@${HOST_JP_1_IP}:${DEPLOY_PATH}";

      - deploy:
          name: 'Publish Website Could HK_1_HOST'
          command:
            ssh-keyscan "${HOST_HK_1_IP}" >> ~/.ssh/known_hosts 2>/dev/null;
            sshpass -p ${HOST_JP_1_PASSWORD}  rsync -avz -e 'ssh -p 22' public/ "${HOST_JP_1_USER}@${HOST_HK_1_IP}:${DEPLOY_PATH}";
